server:
  port: 8200
spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
